name: Test777
favicon: null
layout_spectrum: 0.7737834427971393
typography_spectrum: 0.2863086718134582
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.21376634342595935
  lightness: 0.17834831099025905
  saturation: 0.6142360467929393
  rhythmicContrast: 0.5671870282385498
purpose: []
